server:
  port: 3535

spring:
  servlet:
    multipart:
      enabled: true
      location: C:\Users\user\Documents\KaKaoCloudSchool\data
      max-request-size: 30MB
      max-file-size: 10MB

  datasource:
    url: jdbc:mariadb://localhost:3307/review
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 0902

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  thymeleaf:
    cache: false

Logging:
  level:
    org.hibernate.type.descriptor.sql: trace

com:
  adamsoft:
    upload:
      Path: C:\Users\user\Documents\KaKaoCloudSchool\data