#?? ?? ??
server:
  port: 90

#?????? ?? ??
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/adam
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 0902

  #??? ?? ?? ? ??
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #hibernate query ??? ??
        show_sql: true #hibernate query? ??? ??
  thymeleaf:
    cache: false # ?? ???? ??? ??

#sql? ??? ? ?? ??? ?? ??
Logging:
  level:
    org.hibernate.type.descriptor.sql: trace